// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// --- TopBar Component --- //
function TopBar() {
  return (
    <div className="w-full h-12 bg-[#1a1a1a] border-b border-gray-700 flex items-center justify-between px-4 text-gray-300">
      {/* Left Section */}
      <div className="flex items-center gap-3">
        <button className="w-7 h-7 rounded-full border border-gray-500 flex items-center justify-center">
          💬
        </button>
        <span className="text-sm opacity-80">Untitled</span>
      </div>

      {/* Right Section */}
      <div className="flex items-center gap-4">
        <button className="text-sm hover:text-white">Enter Fullscreen</button>
        <button className="text-sm hover:text-white">Restart</button>

        <button className="px-3 py-1 border border-gray-500 rounded-md text-sm hover:bg-gray-700">
          Login
        </button>

        <button className="px-3 py-1 bg-white text-black rounded-md text-sm">
          Continue with Google
        </button>
      </div>
    </div>
  );
}

// --- Layout --- //
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopBar />
        {children}
      </body>
    </html>
  );
}
